### ISSUE TITLE
Extension is acting on a not nudged site

### ISSUE THREAD

**Issue by dandandandaann** [lgwb89/nudge#62]
I'm only using it to nudge Facebook and Instagam, but it's also appearing on Youtube.   
It is hiding a [vidIQ](https://chrome.google.com/webstore/detail/vidiq-vision-for-youtube/pachckjkecffpdphbpmfolblodfkgbhl) panel just below the playlist box.  

![image](https://user-images.githubusercontent.com/7233639/74987179-5f6b3b00-5419-11ea-802b-58173a017101.png)

**Comment by lgwb89** [comment]
@dandandandaann apologies for this. I toyed with the idea of making the Hider independent of the sites you choose to allow greater customisability. And...looks like I actually went ahead and made that change, but didn't communicate it at all. I'm going to revert the change now so that the Hider will only work on Nudge sites. The update with the bug fix should reach you in around 4-5 days.
